# Generated by Django 4.0 on 2021-12-19 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='videos',
            new_name='video',
        ),
    ]
