# Generated by Django 4.0 on 2021-12-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0002_rename_videos_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='channel_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
