# Generated by Django 4.0 on 2021-12-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0003_video_channel_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='index',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
